---
- name: Install google authenticator PAM module
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    name: libpam-google-authenticator
    state: present

- name: Install google authenticator PAM module
  become: true
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Oracle Linux'
  ansible.builtin.yum:
    name: google-authenticator
    state: present

- name: Add google auth module to PAM
  become: true
  community.general.pamd:
    name: sshd
    type: auth
    control: required
    module_path: pam_google_authenticator.so

- name: Remove password auth from PAM
  become: true
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'Oracle Linux' or ansible_distribution == 'Amazon'
  community.general.pamd:
    name: sshd
    type: auth
    control: substack
    module_path: password-auth
    state: absent

- name: Remove password auth from PAM
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ansible.builtin.replace:
    dest: /etc/pam.d/sshd
    regexp: '^@include common-auth'
    replace: '#@include common-auth'
