---
- name: Set hostkeys according to openssh-version
  when: sshd_version.stdout >= '6.3' and not ssh_host_key_files
  ansible.builtin.set_fact:
    ssh_host_key_files:
      - path: "{{ sshd_config_path }}/ssh_host_rsa_key"
        type: rsa
      - path: "{{ sshd_config_path }}/ssh_host_ecdsa_key"
        type: ecdsa
      - path: "{{ sshd_config_path }}/ssh_host_ed25519_key"
        type: ed25519

- name: Set hostkeys according to openssh-version
  when: sshd_version.stdout >= '6.0' and not ssh_host_key_files
  ansible.builtin.set_fact:
    ssh_host_key_files:
      - path: "{{ sshd_config_path }}/ssh_host_rsa_key"
        type: rsa
      - path: "{{ sshd_config_path }}/ssh_host_ecdsa_key"
        type: ecdsa

- name: Set hostkeys according to openssh-version
  when: sshd_version.stdout >= '5.3' and not ssh_host_key_files
  ansible.builtin.set_fact:
    ssh_host_key_files:
      - path: "{{ sshd_config_path }}/ssh_host_rsa_key"
        type: rsa

- name: Set macs according to openssh-version if openssh >= 7.6
  when: sshd_version.stdout >= '7.6' and not ssh_macs
  ansible.builtin.set_fact:
    ssh_macs: "{{ ssh_macs_76_default }}"

- name: Set macs according to openssh-version if openssh >= 6.6
  when: sshd_version.stdout >= '6.6' and not ssh_macs
  ansible.builtin.set_fact:
    ssh_macs: "{{ ssh_macs_66_default }}"

- name: Set macs according to openssh-version
  when: sshd_version.stdout >= '5.9' and not ssh_macs
  ansible.builtin.set_fact:
    ssh_macs: "{{ ssh_macs_59_default }}"

- name: Set macs according to openssh-version
  when: sshd_version.stdout >= '5.3' and not ssh_macs
  ansible.builtin.set_fact:
    ssh_macs: "{{ ssh_macs_53_default }}"

- name: Set ciphers according to openssh-version if openssh >= 6.6
  when: sshd_version.stdout >= '6.6' and not ssh_ciphers
  ansible.builtin.set_fact:
    ssh_ciphers: "{{ ssh_ciphers_66_default }}"

- name: Set ciphers according to openssh-version
  when: sshd_version.stdout >= '5.3' and not ssh_ciphers
  ansible.builtin.set_fact:
    ssh_ciphers: "{{ ssh_ciphers_53_default }}"

- name: Set kex according to openssh-version if openssh >= 6.6
  when: sshd_version.stdout >= '6.6' and not ssh_kex
  ansible.builtin.set_fact:
    ssh_kex: "{{ ssh_kex_66_default }}"

- name: Set kex according to openssh-version
  when: sshd_version.stdout >= '5.9' and not ssh_kex
  ansible.builtin.set_fact:
    ssh_kex: "{{ ssh_kex_59_default }}"
